# Generated by Django 4.2.2 on 2023-06-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Область'),
            preserve_default=False,
        ),
    ]
