# Generated by Django 4.2.2 on 2023-06-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rates',
        ),
    ]
