# Generated by Django 4.2.2 on 2023-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rates',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='Скан оцінок'),
        ),
    ]
