# Generated by Django 4.2.2 on 2023-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dean',
            field=models.CharField(max_length=45),
        ),
    ]
