# Generated by Django 4.2.2 on 2023-06-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_department_dean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='abit',
            field=models.ManyToManyField(blank=True, related_name='+', to='main.admissionlist', verbose_name='Заявки'),
        ),
    ]
