# Generated by Django 4.2.2 on 2023-06-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_speciality_abit'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_uk',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
