# Generated by Django 4.2.2 on 2023-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_region_region_en_region_region_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='title_uk',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
