# Generated by Django 4.2.2 on 2023-06-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subject_title_en_subject_title_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title_en',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title_uk',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
