# Generated by Django 4.2.2 on 2023-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_subject_title_alter_subject_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidstate',
            name='value_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bidstate',
            name='value_uk',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
