# Generated by Django 4.2.2 on 2023-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bidstate_value_en_bidstate_value_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation_en',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='abbreviation_uk',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='dean_en',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='dean_uk',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
