# Generated by Django 4.2.2 on 2023-06-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_department_abbreviation_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='title_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='title_uk',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
